### ISSUE TITLE
Adição de um campo na API que contém o link da imagem para a previsão

### ISSUE THREAD

**Issue by gentildpinto** [MartinDala/InametStatics--PrevisaodeClimas#2]
Hey! @MartinDala 

Eu lembro de que quando você anunciou esta publicação lançaste um desafio para outros Flutter devs.
De dar um tratamento na aplicação para que tenha uma imagem específica para o clima apresentado, neste senda eu deleguei esse papel para a API que pega o link da imagem que é apresentado no site do INAMET e devolve dentro do objecto da `previsao_de_tempo_actual` e possui o nome de `weather_image_url`.

O objecto retornado matém a mesma estrutura, mas com esse campo adicionado:
```json
{
    "status": 200,
    "provincia": "Luanda",
    "previsao_de_tempo_actual": {
        "weather_image_url": "https://developer.accuweather.com/sites/default/files/06-s.png",
        "Descrição": "Maioritariamente nublado",
        "Temperatura": "30º",
        "Humidade": "61%",
        "Vento": "6km/h (0º N)",
        "Temperatura Sentida": "36º",
        "Temperatura Sentida na Sombra": "33º",
        "Precepitação (última hora)": "0 mm",
        "Ultra Violetas": "Moderado (4)",
        "Cobertura de Nuvens": "85",
        "Pressão": "1011 mb"
    }
}
```

**Comment by gentildpinto** [comment]
Reparei que @antonio-nicolau já aplicou essa mudança rs então estarei linkando a pull request e fechando a issue

**Comment by gentildpinto** [comment]
Reparei que @antonio-nicolau já aplicou essa mudança rs então fecharei a issue

**Comment by MartinDala** [comment]
Grato sou, Bom trabalho feito por si, Parabens

Gentil D. Pinto <notifications@github.com> escreveu no dia quarta,
24/02/2021 à(s) 12:16:

**Comment by antonio-nicolau** [comment]
De boa 👌🏻 o projeto estava bom, só acrescentei o que faltava.
Boa continuação do projeto, vou ajudar no que der
